version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb+srv://ntpd164:QA3x5NxC9*3fWe5@cluster0.1tlq4.mongodb.net/movie_app/?retryWrites=true&w=majority
      - JWT_SECRET=my-secret-token-vip-pro
      - JWT_EXPIRES_IN=100d
    ports:
      - '3000:3000'
    volumes:
      - ./src:/src
      - /src/node_modules
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
